Fixes missed  entity on scan
Bluesy1/ScamScanner pull request #32
Opened 2022-02-14 22:38 UTC by Bluesy1

Closes #31

2022-02-14 22:38 UTC, Bluesy1 commented
Also starts working towards test coverage of bot to confirm things work as expected

2022-02-14 23:01 UTC, Bluesy1 commented
I plan to add more tests before i mege this, but i still want you to review the changes so far Caspar

2022-02-15 03:05 UTC, Bluesy1 commented
I added a few more tests, i can only test ignore conditions though, without getting into creating fake event loops

2022-02-15 03:06 UTC, Bluesy1 commented
At this point, it *should* be ready for a review.

2022-02-15 04:34 UTC, Bluesy1 commented on extensions/config.py
> +@config.child
```suggestion
@config.child
```
Just realized, this also pushes the initial testing for user inputted ban messages.

2022-02-15 22:20 UTC, CasparN requested changes
Seems pretty good to me! 1 thing that should be fixed but besides that its pretty epic

2022-02-15 22:20 UTC, CasparN commented on extensions/reports.py
>                      f"Report for message with the following content has time out. please feel free to resubmit if you "
```suggestion
                    f"Report for message with the following content has timed out. please feel free to resubmit if you "
```

2022-02-15 22:24 UTC, CasparN approved these changes
👏

2022-02-15 22:25 UTC, merged